# Generated by Django 2.2.13 on 2022-09-10 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordermanager', '0001_initial'),
        ('shopmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_info',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='shopmanager.ProductInfo', verbose_name='Информация о продукте'),
        ),
    ]
